### ISSUE TITLE
Don't add /admin automatically to url

### ISSUE THREAD

**Issue by linuxundich** [ziyagenc/phi#2]
I use a revere proxy to access my pihole installation from the internet. In doing so, I change the pihole url from `https://sub.example.com/admin` to `https://sub.example.com` via a rewrite rule - it's just easier to remember.

Everything works, but it looks like you add this /admin to the api call from within your extension automatically. I get the following error message:

![pihole-error](https://github.com/ziyagenc/phi/assets/1716643/990ad0de-ac2d-4f98-ae4e-975fa00d9b0a)

So I'd like to ask to either add a switch to disable the /admin at the end, or to let the user enter the url freely without changing it in the background.

**Comment by ziyagenc** [comment]
That is correct. The current version of Phi builds query URL by adding the path `/admin` to the domain part. Consequently, it fails to cover certain configurations like yours.

The next version will include the improvement you suggested. Vielen Dank for pointing out the issue!

**Comment by ziyagenc** [comment]
The commit ba818c6 brings an update that requires user to enter the complete URL for Pi-hole API. To help the user, information button in the Settings now shows a few examples of valid inputs.

The main branch (compatible with GNOME 45) contains the fix, and the new version of Phi is submitted for review. It should be available soon at GNOME Extensions website.

**Comment by linuxundich** [comment]
Works fine. Thanks!
