### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by amielke** [ziyagenc/phi#4]
Hello,

Please add Support for Gnome 46.

Thank you

**Comment by InvisibleRasta** [comment]
That would be very nice!

**Comment by ziyagenc** [comment]
Hello, 

Thanks for opening this issue. #544ba47 makes Phi compatible with GNOME 46. It should be available at https://extensions.gnome.org soon.

Sorry, it took so long. I have just updated my machine to GNOME 46 and could work on this issue.
